### ISSUE TITLE
Google Cloud Platform issue when downloading the pre-trained models

### ISSUE THREAD

**Issue by amine-mouafi** [ByteXcite/versign#2]
Looks like there are some issues with the Google Cloud Platform when downloading the pre-trained models [https://storage.googleapis.com/versign_db/versign_models.zip](url)
The link return the following error:

`<Error>
<Code>UserProjectAccountProblem</Code>
<Message>User project billing account not in good standing.</Message>
<Details>
The billing account for project 931432439761 is disabled in state absent
</Details>
</Error`

**Comment by DevLucem** [comment]
Yap, the url is invalid.
You might need to create your own models

**Comment by saifkhichi96** [comment]
Duplicate of #3
