### ISSUE TITLE
Not able to download versign_model zip file  

### ISSUE THREAD

**Issue by ankitjain11august** [ByteXcite/versign#3]
Dear Muhammad,

I am not able to download versign_model zip file from **https://storage.googleapis.com/versign_db/versign_models.zip**

Kindly provide me the link where i can download it.

Thank you so much.

**Comment by vj68** [comment]
wget https://storage.googleapis.com/versign_db/versign_models.zip
Cannot access forbidden 403

**Comment by shanethomas1029** [comment]
> wget https://storage.googleapis.com/versign_db/versign_models.zip
> Cannot access forbidden 403

Any Updates on this? did you guys get the link?

**Comment by vj68** [comment]
@shanethomas1029 Nope. It's broken. Might have to create on your own.

**Comment by shanethomas1029** [comment]
> @shanethomas1029 Nope. It's broken. Might have to create on your own.

But How? Can Anyone help?

**Comment by saifkhichi96** [comment]
This repository is no longer maintained. Please refer to my repo [versign-core](https://github.com/saifkhichi96/versign-core) for potential resolution of your issue. Thanks.
